/**
 * eBay Item Specifics(Aspect)の項目名(aspectName)は、eBay Taxonomy APIから
 * 返ってくる英語名をそのまま使う(§117-2: ハードコードせず、eBayのレスポンスに
 * 由来する項目名・候補値のみを使う)。
 * ここでは送信データには影響しない「表示用の日本語訳」だけを補助的に出すための
 * 対訳辞書を用意する。辞書にない項目名はそのまま英語のみ表示する(推測で
 * 訳語を作らない)。
 *
 * 2026-10-04: 「商品仕様の各項目に日本語訳を入れて」という要望への対応。
 */
const ASPECT_NAME_JA: Record<string, string> = {
  Brand: 'ブランド',
  'Brand Name': 'ブランド名',
  Model: '型番・モデル',
  'Model Name': 'モデル名',
  'Model Number': '型番',
  MPN: '製造者品番(MPN)',
  Type: '種類・タイプ',
  Color: 'カラー',
  'Color Family': 'カラー(系統)',
  Material: '材質',
  Size: 'サイズ',
  'Size Type': 'サイズ区分',
  "Size (Men's)": 'サイズ(メンズ)',
  "Size (Women's)": 'サイズ(レディース)',
  Style: 'スタイル',
  Pattern: '柄・パターン',
  Theme: 'テーマ',
  Occasion: '用途・シーン',
  Department: '対象(メンズ/レディース等)',
  Gender: '性別',
  Season: 'シーズン',
  Feature: '特徴・機能',
  Features: '特徴・機能',
  Closure: '開閉方式',
  'Sleeve Length': '袖丈',
  Neckline: 'ネックライン',
  'Country/Region of Manufacture': '製造国',
  'Country of Manufacture': '製造国',
  'Country/Region of Origin': '原産国',
  Era: '年代',
  'Date of Creation': '製作年代',
  'Age Group': '対象年齢層',
  Vintage: 'ヴィンテージ',
  Movement: '駆動方式(ムーブメント)',
  'Case Material': 'ケース素材',
  'Case Size': 'ケースサイズ',
  'Band Material': 'バンド素材',
  'Band Color': 'バンドカラー',
  'Dial Color': 'ダイヤルカラー',
  'Water Resistance': '耐水性',
  Metal: '素材(金属)',
  'Metal Purity': '素材の純度',
  'Main Stone': '主な宝石',
  Stone: '宝石',
  Gemstone: '宝石',
  'Total Carat Weight': '総カラット数',
  'Ring Size': 'リングサイズ',
  'Chain/Necklace Style': 'チェーン/ネックレスのスタイル',
  'Chain Type': 'チェーンの種類',
  Length: '長さ',
  Width: '幅',
  Height: '高さ',
  Depth: '奥行き',
  Weight: '重さ',
  Capacity: '容量',
  'Power Source': '電源・動力',
  Voltage: '電圧',
  Connectivity: '接続方式',
  'Compatible Brand': '対応ブランド',
  'Compatible Model': '対応モデル',
  Signed: '署名の有無',
  'Original/Licensed Reproduction': 'オリジナル/ライセンス複製',
  'Original/Reproduction': 'オリジナル/復刻品',
  Culture: '文化・地域',
  'Region of Origin': '原産地域',
  Religion: '宗教',
  Maker: '製作者・メーカー',
  Artist: '作家・アーティスト',
  Sport: 'スポーツ種目',
  Team: 'チーム',
  League: 'リーグ',
  Player: '選手',
  Franchise: '作品・シリーズ',
  Character: 'キャラクター',
  'Character Family': 'キャラクターファミリー',
  Set: 'セット',
  Convention: '記念・限定イベント',
  Grade: 'グレード(評価)',
  Certification: '鑑定・認証',
  'Certification Number': '鑑定番号',
  'Food Aisle': '食品カテゴリー',
  'Expiration Date': '賞味期限・使用期限',
  Ingredients: '成分・原材料',
  Formulation: '剤型',
  'Skin Type': '対応肌質',
  Volume: '容量',
  'Number of Items': '個数',
  'Item Length': '商品の長さ',
  'Item Height': '商品の高さ',
  'Item Width': '商品の幅',
  'Item Weight': '商品の重さ',
  'Fabric Type': '生地の種類',
  'Lining Material': '裏地素材',
  'Outer Shell Material': '表地素材',
  'Sole Material': 'ソール素材',
  'Upper Material': 'アッパー素材',
  'Toe Shape': 'トゥの形',
  'Heel Height': 'ヒールの高さ',
  'Heel Type': 'ヒールの種類',
  Shade: '色味',
  Finish: '仕上げ',
  Handmade: 'ハンドメイドかどうか',
  Personalized: 'パーソナライズ(名入れ等)',
  Customized: 'カスタム仕様',
  'Vintage/Antique': 'ヴィンテージ/アンティーク',
  'Time Period Manufactured': '製造年代',
  'Production Technique': '製法・技法',
  Shape: '形状',
  'Base Metal': '基材(金属)',
  Fastening: '留め具',
  'Lens Color': 'レンズカラー',
  'Frame Color': 'フレームカラー',
  'Frame Material': 'フレーム素材',
  'Lens Material': 'レンズ素材',
  UPC: 'JANコード相当(UPC)',
  EAN: 'EANコード',
  ISBN: 'ISBN',
  Author: '著者',
  Publisher: '出版社',
  Language: '言語',
  Format: '形式・フォーマット',
  Genre: 'ジャンル',
  Edition: '版・エディション',
  'Publication Year': '出版年',
  Topic: 'トピック・テーマ',

  // 2026-10-04追加: 工具・家電系カテゴリーで実際に未訳だった項目
  'Chuck Type': 'チャックタイプ',
  'Number of Pieces': 'セット点数',
  'Maximum Speed': '最高速度',
  'Minimum Speed': '最低速度',
  'Motor Type': 'モーターの種類',
  'Manufacturer Warranty': 'メーカー保証',
  'Item Diameter': '商品の直径',
  'Country of Origin': '原産国',
  'California Prop 65 Warning': 'カリフォルニア州プロポジション65警告',
  'Durability Guarantee': '耐久性保証',
  'Power': '出力・パワー',
  'Horsepower': '馬力',
  'Battery Type': 'バッテリーの種類',
  'Battery Included': 'バッテリー付属の有無',
  'Cord Length': 'コードの長さ',
  'Drive Type': '駆動方式',
  'Torque': 'トルク',
  'RPM': '回転数(RPM)',
  'Bit Type': 'ビットの種類',
  'Blade Material': '刃の素材',
  'Blade Length': '刃の長さ',
  'Handle Material': '持ち手の素材',
  'Noise Level': '騒音レベル',
  'Energy Efficiency Rating': '省エネ性能',
  'UPC Does Not Apply': 'UPC該当なし',
  'EAN Does Not Apply': 'EAN該当なし',
  'Custom Bundle': 'カスタムバンドルかどうか',
  'Bundle Description': 'バンドル内容の説明',
  'Modified Item': '改造品かどうか',
  'Non-Domestic Product': '非国内向け商品かどうか',
  'California Prop 65 Warning Text': 'カリフォルニア州プロポジション65 警告文',
  'Placement on Vehicle': '取付位置(車両)',
  'Surface Finish': '表面仕上げ',
  'Indoor/Outdoor': '室内用/屋外用',
  'Assembly Required': '組み立ての要否',
  'Assembled Dimensions': '組み立て後のサイズ',
  'Room': '設置場所・部屋',
  'Compatible Make': '対応メーカー(車種)',
  'Compatible Vehicle Make': '対応車両メーカー',
  'Fuel Type': '燃料の種類',
  'Mounting': '取付方法',
};

/** 指定のaspectNameに対応する日本語訳を返す(無ければnull)。 */
export function translateAspectName(aspectName: string): string | null {
  return ASPECT_NAME_JA[aspectName] ?? null;
}
